quarkus.kogito.devservices.enabled=false
quarkus.kogito.data-index.devservices.enabled=false
# Force GraphQL endpoint path
quarkus.smallrye-graphql.root-path=/graphql
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:3000
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,OPTIONS
